// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/social/v1/messages.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendRequestStatus int32

const (
	FriendRequestStatus_STATUS_PENDING  FriendRequestStatus = 0
	FriendRequestStatus_STATUS_ACCEPTED FriendRequestStatus = 1
	FriendRequestStatus_STATUS_DECLINED FriendRequestStatus = 2
)

// Enum value maps for FriendRequestStatus.
var (
	FriendRequestStatus_name = map[int32]string{
		0: "STATUS_PENDING",
		1: "STATUS_ACCEPTED",
		2: "STATUS_DECLINED",
	}
	FriendRequestStatus_value = map[string]int32{
		"STATUS_PENDING":  0,
		"STATUS_ACCEPTED": 1,
		"STATUS_DECLINED": 2,
	}
)

func (x FriendRequestStatus) Enum() *FriendRequestStatus {
	p := new(FriendRequestStatus)
	*p = x
	return p
}

func (x FriendRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_social_v1_messages_proto_enumTypes[0].Descriptor()
}

func (FriendRequestStatus) Type() protoreflect.EnumType {
	return &file_api_social_v1_messages_proto_enumTypes[0]
}

func (x FriendRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendRequestStatus.Descriptor instead.
func (FriendRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{0}
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *uint32                `protobuf:"varint,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	NextCursor    *uint32                `protobuf:"varint,3,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_social_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetCursor() uint32 {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return 0
}

func (x *Pagination) GetNextCursor() uint32 {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return 0
}

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      uint32                 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    uint32                 `protobuf:"varint,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Status        FriendRequestStatus    `protobuf:"varint,4,opt,name=status,proto3,enum=github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequestStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_api_social_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *FriendRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequest) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *FriendRequest) GetReceiverId() uint32 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *FriendRequest) GetStatus() FriendRequestStatus {
	if x != nil {
		return x.Status
	}
	return FriendRequestStatus_STATUS_PENDING
}

type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_api_social_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SendFriendRequestRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *FriendRequest         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_api_social_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SendFriendRequestResponse) GetRequest() *FriendRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ListRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_api_social_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequestsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_api_social_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequestsResponse) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListRequestsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AcceptFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestRequest) Reset() {
	*x = AcceptFriendRequestRequest{}
	mi := &file_api_social_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRequest) ProtoMessage() {}

func (x *AcceptFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptFriendRequestRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AcceptFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *FriendRequest         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestResponse) Reset() {
	*x = AcceptFriendRequestResponse{}
	mi := &file_api_social_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestResponse) ProtoMessage() {}

func (x *AcceptFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptFriendRequestResponse) GetRequest() *FriendRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type DeclineFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestRequest) Reset() {
	*x = DeclineFriendRequestRequest{}
	mi := &file_api_social_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestRequest) ProtoMessage() {}

func (x *DeclineFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DeclineFriendRequestRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type DeclineFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *FriendRequest         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestResponse) Reset() {
	*x = DeclineFriendRequestResponse{}
	mi := &file_api_social_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestResponse) ProtoMessage() {}

func (x *DeclineFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DeclineFriendRequestResponse) GetRequest() *FriendRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type RemoveFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_api_social_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveFriendRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_api_social_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{11}
}

type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_api_social_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ListFriendsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFriendsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendUserIds []uint32               `protobuf:"varint,1,rep,packed,name=friend_user_ids,json=friendUserIds,proto3" json:"friend_user_ids,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_api_social_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *ListFriendsResponse) GetFriendUserIds() []uint32 {
	if x != nil {
		return x.FriendUserIds
	}
	return nil
}

func (x *ListFriendsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_api_social_v1_messages_proto protoreflect.FileDescriptor

const file_api_social_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1capi/social/v1/messages.proto\x127github.com.ademaxweb.msa_messenger.social.api.social.v1\"\x80\x01\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\rH\x00R\x06cursor\x88\x01\x01\x12$\n" +
	"\vnext_cursor\x18\x03 \x01(\rH\x01R\n" +
	"nextCursor\x88\x01\x01B\t\n" +
	"\a_cursorB\x0e\n" +
	"\f_next_cursor\"\xc3\x01\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\rR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\rR\n" +
	"receiverId\x12d\n" +
	"\x06status\x18\x04 \x01(\x0e2L.github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequestStatusR\x06status\"3\n" +
	"\x18SendFriendRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"}\n" +
	"\x19SendFriendRequestResponse\x12`\n" +
	"\arequest\x18\x01 \x01(\v2F.github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequestR\arequest\".\n" +
	"\x13ListRequestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\xdf\x01\n" +
	"\x14ListRequestsResponse\x12b\n" +
	"\brequests\x18\x01 \x03(\v2F.github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequestR\brequests\x12c\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2C.github.com.ademaxweb.msa_messenger.social.api.social.v1.PaginationR\n" +
	"pagination\";\n" +
	"\x1aAcceptFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\"\x7f\n" +
	"\x1bAcceptFriendRequestResponse\x12`\n" +
	"\arequest\x18\x01 \x01(\v2F.github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequestR\arequest\"<\n" +
	"\x1bDeclineFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\"\x80\x01\n" +
	"\x1cDeclineFriendRequestResponse\x12`\n" +
	"\arequest\x18\x01 \x01(\v2F.github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequestR\arequest\".\n" +
	"\x13RemoveFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\x16\n" +
	"\x14RemoveFriendResponse\"\x92\x01\n" +
	"\x12ListFriendsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12c\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2C.github.com.ademaxweb.msa_messenger.social.api.social.v1.PaginationR\n" +
	"pagination\"\xa2\x01\n" +
	"\x13ListFriendsResponse\x12&\n" +
	"\x0ffriend_user_ids\x18\x01 \x03(\rR\rfriendUserIds\x12c\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2C.github.com.ademaxweb.msa_messenger.social.api.social.v1.PaginationR\n" +
	"pagination*]\n" +
	"\x13FriendRequestStatus\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x00\x12\x13\n" +
	"\x0fSTATUS_ACCEPTED\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DECLINED\x10\x02\"\b\b\x03\x10\xff\xff\xff\xff\aB\x17Z\x15pkg/api/social;socialb\x06proto3"

var (
	file_api_social_v1_messages_proto_rawDescOnce sync.Once
	file_api_social_v1_messages_proto_rawDescData []byte
)

func file_api_social_v1_messages_proto_rawDescGZIP() []byte {
	file_api_social_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_social_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_social_v1_messages_proto_rawDesc), len(file_api_social_v1_messages_proto_rawDesc)))
	})
	return file_api_social_v1_messages_proto_rawDescData
}

var file_api_social_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_social_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_social_v1_messages_proto_goTypes = []any{
	(FriendRequestStatus)(0),             // 0: github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequestStatus
	(*Pagination)(nil),                   // 1: github.com.ademaxweb.msa_messenger.social.api.social.v1.Pagination
	(*FriendRequest)(nil),                // 2: github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequest
	(*SendFriendRequestRequest)(nil),     // 3: github.com.ademaxweb.msa_messenger.social.api.social.v1.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),    // 4: github.com.ademaxweb.msa_messenger.social.api.social.v1.SendFriendRequestResponse
	(*ListRequestsRequest)(nil),          // 5: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsRequest
	(*ListRequestsResponse)(nil),         // 6: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsResponse
	(*AcceptFriendRequestRequest)(nil),   // 7: github.com.ademaxweb.msa_messenger.social.api.social.v1.AcceptFriendRequestRequest
	(*AcceptFriendRequestResponse)(nil),  // 8: github.com.ademaxweb.msa_messenger.social.api.social.v1.AcceptFriendRequestResponse
	(*DeclineFriendRequestRequest)(nil),  // 9: github.com.ademaxweb.msa_messenger.social.api.social.v1.DeclineFriendRequestRequest
	(*DeclineFriendRequestResponse)(nil), // 10: github.com.ademaxweb.msa_messenger.social.api.social.v1.DeclineFriendRequestResponse
	(*RemoveFriendRequest)(nil),          // 11: github.com.ademaxweb.msa_messenger.social.api.social.v1.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),         // 12: github.com.ademaxweb.msa_messenger.social.api.social.v1.RemoveFriendResponse
	(*ListFriendsRequest)(nil),           // 13: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsRequest
	(*ListFriendsResponse)(nil),          // 14: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsResponse
}
var file_api_social_v1_messages_proto_depIdxs = []int32{
	0, // 0: github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequest.status:type_name -> github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequestStatus
	2, // 1: github.com.ademaxweb.msa_messenger.social.api.social.v1.SendFriendRequestResponse.request:type_name -> github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequest
	2, // 2: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsResponse.requests:type_name -> github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequest
	1, // 3: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsResponse.pagination:type_name -> github.com.ademaxweb.msa_messenger.social.api.social.v1.Pagination
	2, // 4: github.com.ademaxweb.msa_messenger.social.api.social.v1.AcceptFriendRequestResponse.request:type_name -> github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequest
	2, // 5: github.com.ademaxweb.msa_messenger.social.api.social.v1.DeclineFriendRequestResponse.request:type_name -> github.com.ademaxweb.msa_messenger.social.api.social.v1.FriendRequest
	1, // 6: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsRequest.pagination:type_name -> github.com.ademaxweb.msa_messenger.social.api.social.v1.Pagination
	1, // 7: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsResponse.pagination:type_name -> github.com.ademaxweb.msa_messenger.social.api.social.v1.Pagination
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_social_v1_messages_proto_init() }
func file_api_social_v1_messages_proto_init() {
	if File_api_social_v1_messages_proto != nil {
		return
	}
	file_api_social_v1_messages_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_v1_messages_proto_rawDesc), len(file_api_social_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_social_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_social_v1_messages_proto_depIdxs,
		EnumInfos:         file_api_social_v1_messages_proto_enumTypes,
		MessageInfos:      file_api_social_v1_messages_proto_msgTypes,
	}.Build()
	File_api_social_v1_messages_proto = out.File
	file_api_social_v1_messages_proto_goTypes = nil
	file_api_social_v1_messages_proto_depIdxs = nil
}
