// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/social/v1/service.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_social_v1_service_proto protoreflect.FileDescriptor

const file_api_social_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/social/v1/service.proto\x127github.com.ademaxweb.msa_messenger.social.api.social.v1\x1a\x1capi/social/v1/messages.proto2\xe8\b\n" +
	"\rSocialService\x12\xbc\x01\n" +
	"\x11SendFriendRequest\x12Q.github.com.ademaxweb.msa_messenger.social.api.social.v1.SendFriendRequestRequest\x1aR.github.com.ademaxweb.msa_messenger.social.api.social.v1.SendFriendRequestResponse\"\x00\x12\xad\x01\n" +
	"\fListRequests\x12L.github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsRequest\x1aM.github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsResponse\"\x00\x12\xc2\x01\n" +
	"\x13AcceptFriendRequest\x12S.github.com.ademaxweb.msa_messenger.social.api.social.v1.AcceptFriendRequestRequest\x1aT.github.com.ademaxweb.msa_messenger.social.api.social.v1.AcceptFriendRequestResponse\"\x00\x12\xc5\x01\n" +
	"\x14DeclineFriendRequest\x12T.github.com.ademaxweb.msa_messenger.social.api.social.v1.DeclineFriendRequestRequest\x1aU.github.com.ademaxweb.msa_messenger.social.api.social.v1.DeclineFriendRequestResponse\"\x00\x12\xad\x01\n" +
	"\fRemoveFriend\x12L.github.com.ademaxweb.msa_messenger.social.api.social.v1.RemoveFriendRequest\x1aM.github.com.ademaxweb.msa_messenger.social.api.social.v1.RemoveFriendResponse\"\x00\x12\xaa\x01\n" +
	"\vListFriends\x12K.github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsRequest\x1aL.github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsResponse\"\x00B\x17Z\x15pkg/api/social;socialb\x06proto3"

var file_api_social_v1_service_proto_goTypes = []any{
	(*SendFriendRequestRequest)(nil),     // 0: github.com.ademaxweb.msa_messenger.social.api.social.v1.SendFriendRequestRequest
	(*ListRequestsRequest)(nil),          // 1: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsRequest
	(*AcceptFriendRequestRequest)(nil),   // 2: github.com.ademaxweb.msa_messenger.social.api.social.v1.AcceptFriendRequestRequest
	(*DeclineFriendRequestRequest)(nil),  // 3: github.com.ademaxweb.msa_messenger.social.api.social.v1.DeclineFriendRequestRequest
	(*RemoveFriendRequest)(nil),          // 4: github.com.ademaxweb.msa_messenger.social.api.social.v1.RemoveFriendRequest
	(*ListFriendsRequest)(nil),           // 5: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsRequest
	(*SendFriendRequestResponse)(nil),    // 6: github.com.ademaxweb.msa_messenger.social.api.social.v1.SendFriendRequestResponse
	(*ListRequestsResponse)(nil),         // 7: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsResponse
	(*AcceptFriendRequestResponse)(nil),  // 8: github.com.ademaxweb.msa_messenger.social.api.social.v1.AcceptFriendRequestResponse
	(*DeclineFriendRequestResponse)(nil), // 9: github.com.ademaxweb.msa_messenger.social.api.social.v1.DeclineFriendRequestResponse
	(*RemoveFriendResponse)(nil),         // 10: github.com.ademaxweb.msa_messenger.social.api.social.v1.RemoveFriendResponse
	(*ListFriendsResponse)(nil),          // 11: github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsResponse
}
var file_api_social_v1_service_proto_depIdxs = []int32{
	0,  // 0: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.SendFriendRequest:input_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.SendFriendRequestRequest
	1,  // 1: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.ListRequests:input_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsRequest
	2,  // 2: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.AcceptFriendRequest:input_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.AcceptFriendRequestRequest
	3,  // 3: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.DeclineFriendRequest:input_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.DeclineFriendRequestRequest
	4,  // 4: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.RemoveFriend:input_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.RemoveFriendRequest
	5,  // 5: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.ListFriends:input_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsRequest
	6,  // 6: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.SendFriendRequest:output_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.SendFriendRequestResponse
	7,  // 7: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.ListRequests:output_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.ListRequestsResponse
	8,  // 8: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.AcceptFriendRequest:output_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.AcceptFriendRequestResponse
	9,  // 9: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.DeclineFriendRequest:output_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.DeclineFriendRequestResponse
	10, // 10: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.RemoveFriend:output_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.RemoveFriendResponse
	11, // 11: github.com.ademaxweb.msa_messenger.social.api.social.v1.SocialService.ListFriends:output_type -> github.com.ademaxweb.msa_messenger.social.api.social.v1.ListFriendsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_social_v1_service_proto_init() }
func file_api_social_v1_service_proto_init() {
	if File_api_social_v1_service_proto != nil {
		return
	}
	file_api_social_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_v1_service_proto_rawDesc), len(file_api_social_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_social_v1_service_proto_goTypes,
		DependencyIndexes: file_api_social_v1_service_proto_depIdxs,
	}.Build()
	File_api_social_v1_service_proto = out.File
	file_api_social_v1_service_proto_goTypes = nil
	file_api_social_v1_service_proto_depIdxs = nil
}
