// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/chat/v1/service.proto

package chat

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_chat_v1_service_proto protoreflect.FileDescriptor

const file_api_chat_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/chat/v1/service.proto\x12.github.com.ademaxweb.msa_messenger.chat.api.v1\x1a\x1aapi/chat/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto2\xba\n" +
	"\n" +
	"\vChatService\x12\xc6\x01\n" +
	"\x10CreateDirectChat\x12G.github.com.ademaxweb.msa_messenger.chat.api.v1.CreateDirectChatRequest\x1aH.github.com.ademaxweb.msa_messenger.chat.api.v1.CreateDirectChatResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/chats/direct\x12\xab\x01\n" +
	"\aGetChat\x12>.github.com.ademaxweb.msa_messenger.chat.api.v1.GetChatRequest\x1a?.github.com.ademaxweb.msa_messenger.chat.api.v1.GetChatResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/chats/{chat_id}\x12\xb3\x01\n" +
	"\rListUserChats\x12D.github.com.ademaxweb.msa_messenger.chat.api.v1.ListUserChatsRequest\x1aE.github.com.ademaxweb.msa_messenger.chat.api.v1.ListUserChatsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/chats\x12\xcb\x01\n" +
	"\x0fListChatMembers\x12F.github.com.ademaxweb.msa_messenger.chat.api.v1.ListChatMembersRequest\x1aG.github.com.ademaxweb.msa_messenger.chat.api.v1.ListChatMembersResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/chats/{chat_id}/members\x12\xc3\x01\n" +
	"\vSendMessage\x12B.github.com.ademaxweb.msa_messenger.chat.api.v1.SendMessageRequest\x1aC.github.com.ademaxweb.msa_messenger.chat.api.v1.SendMessageResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/chats/{chat_id}/messages\x12\xc3\x01\n" +
	"\fListMessages\x12C.github.com.ademaxweb.msa_messenger.chat.api.v1.ListMessagesRequest\x1aD.github.com.ademaxweb.msa_messenger.chat.api.v1.ListMessagesResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/chats/{chat_id}/messages\x12\xa3\x01\n" +
	"\x0eStreamMessages\x12E.github.com.ademaxweb.msa_messenger.chat.api.v1.StreamMessagesRequest\x1aF.github.com.ademaxweb.msa_messenger.chat.api.v1.StreamMessagesResponse\"\x000\x01B\x13Z\x11pkg/api/chat;chatb\x06proto3"

var file_api_chat_v1_service_proto_goTypes = []any{
	(*CreateDirectChatRequest)(nil),  // 0: github.com.ademaxweb.msa_messenger.chat.api.v1.CreateDirectChatRequest
	(*GetChatRequest)(nil),           // 1: github.com.ademaxweb.msa_messenger.chat.api.v1.GetChatRequest
	(*ListUserChatsRequest)(nil),     // 2: github.com.ademaxweb.msa_messenger.chat.api.v1.ListUserChatsRequest
	(*ListChatMembersRequest)(nil),   // 3: github.com.ademaxweb.msa_messenger.chat.api.v1.ListChatMembersRequest
	(*SendMessageRequest)(nil),       // 4: github.com.ademaxweb.msa_messenger.chat.api.v1.SendMessageRequest
	(*ListMessagesRequest)(nil),      // 5: github.com.ademaxweb.msa_messenger.chat.api.v1.ListMessagesRequest
	(*StreamMessagesRequest)(nil),    // 6: github.com.ademaxweb.msa_messenger.chat.api.v1.StreamMessagesRequest
	(*CreateDirectChatResponse)(nil), // 7: github.com.ademaxweb.msa_messenger.chat.api.v1.CreateDirectChatResponse
	(*GetChatResponse)(nil),          // 8: github.com.ademaxweb.msa_messenger.chat.api.v1.GetChatResponse
	(*ListUserChatsResponse)(nil),    // 9: github.com.ademaxweb.msa_messenger.chat.api.v1.ListUserChatsResponse
	(*ListChatMembersResponse)(nil),  // 10: github.com.ademaxweb.msa_messenger.chat.api.v1.ListChatMembersResponse
	(*SendMessageResponse)(nil),      // 11: github.com.ademaxweb.msa_messenger.chat.api.v1.SendMessageResponse
	(*ListMessagesResponse)(nil),     // 12: github.com.ademaxweb.msa_messenger.chat.api.v1.ListMessagesResponse
	(*StreamMessagesResponse)(nil),   // 13: github.com.ademaxweb.msa_messenger.chat.api.v1.StreamMessagesResponse
}
var file_api_chat_v1_service_proto_depIdxs = []int32{
	0,  // 0: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.CreateDirectChat:input_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.CreateDirectChatRequest
	1,  // 1: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.GetChat:input_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.GetChatRequest
	2,  // 2: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.ListUserChats:input_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.ListUserChatsRequest
	3,  // 3: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.ListChatMembers:input_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.ListChatMembersRequest
	4,  // 4: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.SendMessage:input_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.SendMessageRequest
	5,  // 5: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.ListMessages:input_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.ListMessagesRequest
	6,  // 6: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.StreamMessages:input_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.StreamMessagesRequest
	7,  // 7: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.CreateDirectChat:output_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.CreateDirectChatResponse
	8,  // 8: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.GetChat:output_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.GetChatResponse
	9,  // 9: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.ListUserChats:output_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.ListUserChatsResponse
	10, // 10: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.ListChatMembers:output_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.ListChatMembersResponse
	11, // 11: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.SendMessage:output_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.SendMessageResponse
	12, // 12: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.ListMessages:output_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.ListMessagesResponse
	13, // 13: github.com.ademaxweb.msa_messenger.chat.api.v1.ChatService.StreamMessages:output_type -> github.com.ademaxweb.msa_messenger.chat.api.v1.StreamMessagesResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_chat_v1_service_proto_init() }
func file_api_chat_v1_service_proto_init() {
	if File_api_chat_v1_service_proto != nil {
		return
	}
	file_api_chat_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_service_proto_rawDesc), len(file_api_chat_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_v1_service_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_service_proto_depIdxs,
	}.Build()
	File_api_chat_v1_service_proto = out.File
	file_api_chat_v1_service_proto_goTypes = nil
	file_api_chat_v1_service_proto_depIdxs = nil
}
