// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/auth/v1/messages.proto

package auth

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Учетные данные пользователя для аутентификации
type Credentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email пользователя
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Пароль пользователя
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_api_auth_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Токены аутентификации, возвращаемые при успешном входе
type Token struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access token для авторизации API запросов
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Refresh token для обновления access token
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Идентификатор пользователя, связанный с токенами
	UserId        uint32 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_api_auth_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Token) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Запрос на регистрацию нового пользователя в системе
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Учетные данные для создания нового аккаунта
	Credentials   *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_auth_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// Ответ на успешную регистрацию пользователя
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор созданного пользователя
	UserId        uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_auth_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Запрос на аутентификацию существующего пользователя
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Учетные данные для входа в систему
	Credentials   *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_auth_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// Ответ на успешную аутентификацию
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Сгенерированные токены доступа
	Token         *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_auth_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

// Запрос на обновление access token с помощью refresh token
type RefreshRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Refresh token, полученный при предыдущей аутентификации
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_api_auth_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Ответ с обновленными токенами доступа
type RefreshResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Новые токены доступа
	Token         *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_api_auth_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_api_auth_v1_messages_proto protoreflect.FileDescriptor

const file_api_auth_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/auth/v1/messages.proto\x123github.com.ademaxweb.msa_messenger.auth.api.auth.v1\x1a\x1bbuf/validate/validate.proto\"W\n" +
	"\vCredentials\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02`\x01R\x05email\x12&\n" +
	"\bpassword\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\bR\bpassword\"h\n" +
	"\x05Token\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"}\n" +
	"\x0fRegisterRequest\x12j\n" +
	"\vcredentials\x18\x01 \x01(\v2@.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.CredentialsB\x06\xbaH\x03\xc8\x01\x01R\vcredentials\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"z\n" +
	"\fLoginRequest\x12j\n" +
	"\vcredentials\x18\x01 \x01(\v2@.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.CredentialsB\x06\xbaH\x03\xc8\x01\x01R\vcredentials\"a\n" +
	"\rLoginResponse\x12P\n" +
	"\x05token\x18\x01 \x01(\v2:.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.TokenR\x05token\"A\n" +
	"\x0eRefreshRequest\x12/\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\frefreshToken\"c\n" +
	"\x0fRefreshResponse\x12P\n" +
	"\x05token\x18\x01 \x01(\v2:.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.TokenR\x05tokenB\x13Z\x11pkg/api/auth;authb\x06proto3"

var (
	file_api_auth_v1_messages_proto_rawDescOnce sync.Once
	file_api_auth_v1_messages_proto_rawDescData []byte
)

func file_api_auth_v1_messages_proto_rawDescGZIP() []byte {
	file_api_auth_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_messages_proto_rawDesc), len(file_api_auth_v1_messages_proto_rawDesc)))
	})
	return file_api_auth_v1_messages_proto_rawDescData
}

var file_api_auth_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_auth_v1_messages_proto_goTypes = []any{
	(*Credentials)(nil),      // 0: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.Credentials
	(*Token)(nil),            // 1: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.Token
	(*RegisterRequest)(nil),  // 2: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RegisterRequest
	(*RegisterResponse)(nil), // 3: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RegisterResponse
	(*LoginRequest)(nil),     // 4: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginRequest
	(*LoginResponse)(nil),    // 5: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginResponse
	(*RefreshRequest)(nil),   // 6: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RefreshRequest
	(*RefreshResponse)(nil),  // 7: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RefreshResponse
}
var file_api_auth_v1_messages_proto_depIdxs = []int32{
	0, // 0: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RegisterRequest.credentials:type_name -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.Credentials
	0, // 1: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginRequest.credentials:type_name -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.Credentials
	1, // 2: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginResponse.token:type_name -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.Token
	1, // 3: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RefreshResponse.token:type_name -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.Token
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_auth_v1_messages_proto_init() }
func file_api_auth_v1_messages_proto_init() {
	if File_api_auth_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_messages_proto_rawDesc), len(file_api_auth_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_messages_proto_msgTypes,
	}.Build()
	File_api_auth_v1_messages_proto = out.File
	file_api_auth_v1_messages_proto_goTypes = nil
	file_api_auth_v1_messages_proto_depIdxs = nil
}
