// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/auth/v1/service.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/auth/v1/service.proto\x123github.com.ademaxweb.msa_messenger.auth.api.auth.v1\x1a\x1aapi/auth/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto2\xb1\x04\n" +
	"\vAuthService\x12\xb9\x01\n" +
	"\bRegister\x12D.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RegisterRequest\x1aE.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RegisterResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12\xad\x01\n" +
	"\x05Login\x12A.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginRequest\x1aB.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12\xb5\x01\n" +
	"\aRefresh\x12C.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RefreshRequest\x1aD.github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RefreshResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refreshB\x13Z\x11pkg/api/auth;authb\x06proto3"

var file_api_auth_v1_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RegisterRequest
	(*LoginRequest)(nil),     // 1: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginRequest
	(*RefreshRequest)(nil),   // 2: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RefreshRequest
	(*RegisterResponse)(nil), // 3: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RegisterResponse
	(*LoginResponse)(nil),    // 4: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginResponse
	(*RefreshResponse)(nil),  // 5: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RefreshResponse
}
var file_api_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.AuthService.Register:input_type -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RegisterRequest
	1, // 1: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.AuthService.Login:input_type -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginRequest
	2, // 2: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.AuthService.Refresh:input_type -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RefreshRequest
	3, // 3: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.AuthService.Register:output_type -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RegisterResponse
	4, // 4: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.AuthService.Login:output_type -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.LoginResponse
	5, // 5: github.com.ademaxweb.msa_messenger.auth.api.auth.v1.AuthService.Refresh:output_type -> github.com.ademaxweb.msa_messenger.auth.api.auth.v1.RefreshResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_service_proto_init() }
func file_api_auth_v1_service_proto_init() {
	if File_api_auth_v1_service_proto != nil {
		return
	}
	file_api_auth_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_service_proto_rawDesc), len(file_api_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_service_proto = out.File
	file_api_auth_v1_service_proto_goTypes = nil
	file_api_auth_v1_service_proto_depIdxs = nil
}
