// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chat/internal/app/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChatRepository creates a new instance of MockChatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatRepository {
	mock := &MockChatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatRepository is an autogenerated mock type for the ChatRepository type
type MockChatRepository struct {
	mock.Mock
}

type MockChatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatRepository) EXPECT() *MockChatRepository_Expecter {
	return &MockChatRepository_Expecter{mock: &_m.Mock}
}

// CreateChat provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) CreateChat(chat *models.Chat, members []uint32) (uint32, error) {
	ret := _mock.Called(chat, members)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Chat, []uint32) (uint32, error)); ok {
		return returnFunc(chat, members)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Chat, []uint32) uint32); ok {
		r0 = returnFunc(chat, members)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Chat, []uint32) error); ok {
		r1 = returnFunc(chat, members)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepository_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type MockChatRepository_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - chat *models.Chat
//   - members []uint32
func (_e *MockChatRepository_Expecter) CreateChat(chat interface{}, members interface{}) *MockChatRepository_CreateChat_Call {
	return &MockChatRepository_CreateChat_Call{Call: _e.mock.On("CreateChat", chat, members)}
}

func (_c *MockChatRepository_CreateChat_Call) Run(run func(chat *models.Chat, members []uint32)) *MockChatRepository_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Chat
		if args[0] != nil {
			arg0 = args[0].(*models.Chat)
		}
		var arg1 []uint32
		if args[1] != nil {
			arg1 = args[1].([]uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatRepository_CreateChat_Call) Return(v uint32, err error) *MockChatRepository_CreateChat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockChatRepository_CreateChat_Call) RunAndReturn(run func(chat *models.Chat, members []uint32) (uint32, error)) *MockChatRepository_CreateChat_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessage provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) CreateMessage(message *models.Message) (uint32, error) {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Message) (uint32, error)); ok {
		return returnFunc(message)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Message) uint32); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Message) error); ok {
		r1 = returnFunc(message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepository_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MockChatRepository_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - message *models.Message
func (_e *MockChatRepository_Expecter) CreateMessage(message interface{}) *MockChatRepository_CreateMessage_Call {
	return &MockChatRepository_CreateMessage_Call{Call: _e.mock.On("CreateMessage", message)}
}

func (_c *MockChatRepository_CreateMessage_Call) Run(run func(message *models.Message)) *MockChatRepository_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Message
		if args[0] != nil {
			arg0 = args[0].(*models.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatRepository_CreateMessage_Call) Return(v uint32, err error) *MockChatRepository_CreateMessage_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockChatRepository_CreateMessage_Call) RunAndReturn(run func(message *models.Message) (uint32, error)) *MockChatRepository_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatByID provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) GetChatByID(id uint32) (*models.Chat, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetChatByID")
	}

	var r0 *models.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint32) (*models.Chat, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint32) *models.Chat); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepository_GetChatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatByID'
type MockChatRepository_GetChatByID_Call struct {
	*mock.Call
}

// GetChatByID is a helper method to define mock.On call
//   - id uint32
func (_e *MockChatRepository_Expecter) GetChatByID(id interface{}) *MockChatRepository_GetChatByID_Call {
	return &MockChatRepository_GetChatByID_Call{Call: _e.mock.On("GetChatByID", id)}
}

func (_c *MockChatRepository_GetChatByID_Call) Run(run func(id uint32)) *MockChatRepository_GetChatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatRepository_GetChatByID_Call) Return(chat *models.Chat, err error) *MockChatRepository_GetChatByID_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChatRepository_GetChatByID_Call) RunAndReturn(run func(id uint32) (*models.Chat, error)) *MockChatRepository_GetChatByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatMembersByChatID provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) GetChatMembersByChatID(id uint32) ([]uint32, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetChatMembersByChatID")
	}

	var r0 []uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint32) ([]uint32, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint32) []uint32); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepository_GetChatMembersByChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatMembersByChatID'
type MockChatRepository_GetChatMembersByChatID_Call struct {
	*mock.Call
}

// GetChatMembersByChatID is a helper method to define mock.On call
//   - id uint32
func (_e *MockChatRepository_Expecter) GetChatMembersByChatID(id interface{}) *MockChatRepository_GetChatMembersByChatID_Call {
	return &MockChatRepository_GetChatMembersByChatID_Call{Call: _e.mock.On("GetChatMembersByChatID", id)}
}

func (_c *MockChatRepository_GetChatMembersByChatID_Call) Run(run func(id uint32)) *MockChatRepository_GetChatMembersByChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatRepository_GetChatMembersByChatID_Call) Return(uint32s []uint32, err error) *MockChatRepository_GetChatMembersByChatID_Call {
	_c.Call.Return(uint32s, err)
	return _c
}

func (_c *MockChatRepository_GetChatMembersByChatID_Call) RunAndReturn(run func(id uint32) ([]uint32, error)) *MockChatRepository_GetChatMembersByChatID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatMessagesByChatID provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) GetChatMessagesByChatID(id uint32) ([]models.Message, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetChatMessagesByChatID")
	}

	var r0 []models.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint32) ([]models.Message, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint32) []models.Message); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepository_GetChatMessagesByChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatMessagesByChatID'
type MockChatRepository_GetChatMessagesByChatID_Call struct {
	*mock.Call
}

// GetChatMessagesByChatID is a helper method to define mock.On call
//   - id uint32
func (_e *MockChatRepository_Expecter) GetChatMessagesByChatID(id interface{}) *MockChatRepository_GetChatMessagesByChatID_Call {
	return &MockChatRepository_GetChatMessagesByChatID_Call{Call: _e.mock.On("GetChatMessagesByChatID", id)}
}

func (_c *MockChatRepository_GetChatMessagesByChatID_Call) Run(run func(id uint32)) *MockChatRepository_GetChatMessagesByChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatRepository_GetChatMessagesByChatID_Call) Return(messages []models.Message, err error) *MockChatRepository_GetChatMessagesByChatID_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockChatRepository_GetChatMessagesByChatID_Call) RunAndReturn(run func(id uint32) ([]models.Message, error)) *MockChatRepository_GetChatMessagesByChatID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserChatsByUserID provides a mock function for the type MockChatRepository
func (_mock *MockChatRepository) GetUserChatsByUserID(id uint32) ([]models.Chat, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserChatsByUserID")
	}

	var r0 []models.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint32) ([]models.Chat, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint32) []models.Chat); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepository_GetUserChatsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserChatsByUserID'
type MockChatRepository_GetUserChatsByUserID_Call struct {
	*mock.Call
}

// GetUserChatsByUserID is a helper method to define mock.On call
//   - id uint32
func (_e *MockChatRepository_Expecter) GetUserChatsByUserID(id interface{}) *MockChatRepository_GetUserChatsByUserID_Call {
	return &MockChatRepository_GetUserChatsByUserID_Call{Call: _e.mock.On("GetUserChatsByUserID", id)}
}

func (_c *MockChatRepository_GetUserChatsByUserID_Call) Run(run func(id uint32)) *MockChatRepository_GetUserChatsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatRepository_GetUserChatsByUserID_Call) Return(chats []models.Chat, err error) *MockChatRepository_GetUserChatsByUserID_Call {
	_c.Call.Return(chats, err)
	return _c
}

func (_c *MockChatRepository_GetUserChatsByUserID_Call) RunAndReturn(run func(id uint32) ([]models.Chat, error)) *MockChatRepository_GetUserChatsByUserID_Call {
	_c.Call.Return(run)
	return _c
}
