// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/users/v1/messages.proto

package users

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Модель профиля пользователя системы
type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор пользователя в системе
	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Отображаемое имя пользователя (никнейм)
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Краткое описание пользователя, статус или информация "О себе"
	Bio string `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	// URL аватара пользователя
	AvatarUrl     string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_users_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// Параметры пагинации для управления выводом списков
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Максимальное количество элементов на странице
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Текущая позиция курсора для пагинации (опционально)
	Cursor *uint32 `protobuf:"varint,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	// Позиция курсора для следующей страницы результатов (опционально)
	NextCursor    *uint32 `protobuf:"varint,3,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_users_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetCursor() uint32 {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return 0
}

func (x *Pagination) GetNextCursor() uint32 {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return 0
}

// Запрос на создание нового профиля пользователя
type CreateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор пользователя
	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Отображаемое имя пользователя (обязательное поле)
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Краткое описание пользователя (опционально)
	Bio *string `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	// URL аватара пользователя (опционально)
	AvatarUrl     *string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProfileRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// Ответ на запрос создания профиля пользователя
type CreateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Созданный профиль пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProfileResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// Запрос на обновление существующего профиля пользователя
type UpdateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор обновляемого пользователя
	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Новое отображаемое имя пользователя (опционально)
	Nickname *string `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	// Новое описание пользователя (опционально)
	Bio *string `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	// Новый URL аватара пользователя (опционально)
	AvatarUrl     *string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// Ответ на запрос обновления профиля пользователя
type UpdateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Обновленный профиль пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProfileResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// Запрос на получение профиля пользователя по идентификатору
type GetProfileByIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор искомого пользователя
	UserId        uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDRequest) Reset() {
	*x = GetProfileByIDRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDRequest) ProtoMessage() {}

func (x *GetProfileByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfileByIDRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Ответ на запрос получения профиля по идентификатору
type GetProfileByIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Найденный профиль пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDResponse) Reset() {
	*x = GetProfileByIDResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDResponse) ProtoMessage() {}

func (x *GetProfileByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileByIDResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// Запрос на получение профиля пользователя по никнейму
type GetProfileByNicknameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отображаемое имя пользователя для поиска
	Nickname      string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByNicknameRequest) Reset() {
	*x = GetProfileByNicknameRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByNicknameRequest) ProtoMessage() {}

func (x *GetProfileByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByNicknameRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileByNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// Ответ на запрос получения профиля по никнейму
type GetProfileByNicknameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Найденный профиль пользователя
	UserProfile   *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByNicknameResponse) Reset() {
	*x = GetProfileByNicknameResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByNicknameResponse) ProtoMessage() {}

func (x *GetProfileByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByNicknameResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GetProfileByNicknameResponse) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

// Запрос на поиск пользователей по частичному совпадению никнейма
type SearchProfileByNicknameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Строка поискового запроса (часть никнейма для поиска)
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Параметры пагинации для управления результатами поиска
	Pagination    *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProfileByNicknameRequest) Reset() {
	*x = SearchProfileByNicknameRequest{}
	mi := &file_api_users_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProfileByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProfileByNicknameRequest) ProtoMessage() {}

func (x *SearchProfileByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProfileByNicknameRequest.ProtoReflect.Descriptor instead.
func (*SearchProfileByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SearchProfileByNicknameRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProfileByNicknameRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Ответ на запрос поиска пользователей
type SearchProfileByNicknameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список найденных профилей пользователей
	Results []*UserProfile `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Информация о пагинации для навигации по результатам
	Pagination    *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProfileByNicknameResponse) Reset() {
	*x = SearchProfileByNicknameResponse{}
	mi := &file_api_users_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProfileByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProfileByNicknameResponse) ProtoMessage() {}

func (x *SearchProfileByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProfileByNicknameResponse.ProtoReflect.Descriptor instead.
func (*SearchProfileByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *SearchProfileByNicknameResponse) GetResults() []*UserProfile {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchProfileByNicknameResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_api_users_v1_messages_proto protoreflect.FileDescriptor

const file_api_users_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/users/v1/messages.proto\x125github.com.ademaxweb.msa_messenger.users.api.users.v1\x1a\x1bbuf/validate/validate.proto\"s\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"\x80\x01\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\rH\x00R\x06cursor\x88\x01\x01\x12$\n" +
	"\vnext_cursor\x18\x03 \x01(\rH\x01R\n" +
	"nextCursor\x88\x01\x01B\t\n" +
	"\a_cursorB\x0e\n" +
	"\f_next_cursor\"\xab\x01\n" +
	"\x14CreateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12(\n" +
	"\bnickname\x18\x02 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x05\x18\x14R\bnickname\x12\x15\n" +
	"\x03bio\x18\x03 \x01(\tH\x00R\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x01R\tavatarUrl\x88\x01\x01B\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_url\"~\n" +
	"\x15CreateProfileResponse\x12e\n" +
	"\fuser_profile\x18\x01 \x01(\v2B.github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfileR\vuserProfile\"\xc2\x01\n" +
	"\x14UpdateProfileRequest\x12\x1f\n" +
	"\auser_id\x18\x01 \x01(\rB\x06\xbaH\x03\xc8\x01\x01R\x06userId\x12*\n" +
	"\bnickname\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x05\x18\x14H\x00R\bnickname\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\x03 \x01(\tH\x01R\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x02R\tavatarUrl\x88\x01\x01B\v\n" +
	"\t_nicknameB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_avatar_url\"~\n" +
	"\x15UpdateProfileResponse\x12e\n" +
	"\fuser_profile\x18\x01 \x01(\v2B.github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfileR\vuserProfile\"8\n" +
	"\x15GetProfileByIDRequest\x12\x1f\n" +
	"\auser_id\x18\x01 \x01(\rB\x06\xbaH\x03\xc8\x01\x01R\x06userId\"\x7f\n" +
	"\x16GetProfileByIDResponse\x12e\n" +
	"\fuser_profile\x18\x01 \x01(\v2B.github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfileR\vuserProfile\"G\n" +
	"\x1bGetProfileByNicknameRequest\x12(\n" +
	"\bnickname\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x05\x18\x14R\bnickname\"\x85\x01\n" +
	"\x1cGetProfileByNicknameResponse\x12e\n" +
	"\fuser_profile\x18\x01 \x01(\v2B.github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfileR\vuserProfile\"\xa5\x01\n" +
	"\x1eSearchProfileByNicknameRequest\x12 \n" +
	"\x05query\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x03R\x05query\x12a\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2A.github.com.ademaxweb.msa_messenger.users.api.users.v1.PaginationR\n" +
	"pagination\"\xe2\x01\n" +
	"\x1fSearchProfileByNicknameResponse\x12\\\n" +
	"\aresults\x18\x01 \x03(\v2B.github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfileR\aresults\x12a\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2A.github.com.ademaxweb.msa_messenger.users.api.users.v1.PaginationR\n" +
	"paginationB\x15Z\x13pkg/api/users;usersb\x06proto3"

var (
	file_api_users_v1_messages_proto_rawDescOnce sync.Once
	file_api_users_v1_messages_proto_rawDescData []byte
)

func file_api_users_v1_messages_proto_rawDescGZIP() []byte {
	file_api_users_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_users_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_v1_messages_proto_rawDesc), len(file_api_users_v1_messages_proto_rawDesc)))
	})
	return file_api_users_v1_messages_proto_rawDescData
}

var file_api_users_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_users_v1_messages_proto_goTypes = []any{
	(*UserProfile)(nil),                     // 0: github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfile
	(*Pagination)(nil),                      // 1: github.com.ademaxweb.msa_messenger.users.api.users.v1.Pagination
	(*CreateProfileRequest)(nil),            // 2: github.com.ademaxweb.msa_messenger.users.api.users.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),           // 3: github.com.ademaxweb.msa_messenger.users.api.users.v1.CreateProfileResponse
	(*UpdateProfileRequest)(nil),            // 4: github.com.ademaxweb.msa_messenger.users.api.users.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),           // 5: github.com.ademaxweb.msa_messenger.users.api.users.v1.UpdateProfileResponse
	(*GetProfileByIDRequest)(nil),           // 6: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByIDRequest
	(*GetProfileByIDResponse)(nil),          // 7: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByIDResponse
	(*GetProfileByNicknameRequest)(nil),     // 8: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByNicknameRequest
	(*GetProfileByNicknameResponse)(nil),    // 9: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByNicknameResponse
	(*SearchProfileByNicknameRequest)(nil),  // 10: github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameRequest
	(*SearchProfileByNicknameResponse)(nil), // 11: github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameResponse
}
var file_api_users_v1_messages_proto_depIdxs = []int32{
	0, // 0: github.com.ademaxweb.msa_messenger.users.api.users.v1.CreateProfileResponse.user_profile:type_name -> github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfile
	0, // 1: github.com.ademaxweb.msa_messenger.users.api.users.v1.UpdateProfileResponse.user_profile:type_name -> github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfile
	0, // 2: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByIDResponse.user_profile:type_name -> github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfile
	0, // 3: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByNicknameResponse.user_profile:type_name -> github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfile
	1, // 4: github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameRequest.pagination:type_name -> github.com.ademaxweb.msa_messenger.users.api.users.v1.Pagination
	0, // 5: github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameResponse.results:type_name -> github.com.ademaxweb.msa_messenger.users.api.users.v1.UserProfile
	1, // 6: github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameResponse.pagination:type_name -> github.com.ademaxweb.msa_messenger.users.api.users.v1.Pagination
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_users_v1_messages_proto_init() }
func file_api_users_v1_messages_proto_init() {
	if File_api_users_v1_messages_proto != nil {
		return
	}
	file_api_users_v1_messages_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_users_v1_messages_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_users_v1_messages_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_messages_proto_rawDesc), len(file_api_users_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_users_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_users_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_users_v1_messages_proto_msgTypes,
	}.Build()
	File_api_users_v1_messages_proto = out.File
	file_api_users_v1_messages_proto_goTypes = nil
	file_api_users_v1_messages_proto_depIdxs = nil
}
