// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/users/v1/service.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_users_v1_service_proto protoreflect.FileDescriptor

const file_api_users_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/users/v1/service.proto\x125github.com.ademaxweb.msa_messenger.users.api.users.v1\x1a\x1bapi/users/v1/messages.proto2\xaf\a\n" +
	"\fUsersService\x12\xac\x01\n" +
	"\rCreateProfile\x12K.github.com.ademaxweb.msa_messenger.users.api.users.v1.CreateProfileRequest\x1aL.github.com.ademaxweb.msa_messenger.users.api.users.v1.CreateProfileResponse\"\x00\x12\xac\x01\n" +
	"\rUpdateProfile\x12K.github.com.ademaxweb.msa_messenger.users.api.users.v1.UpdateProfileRequest\x1aL.github.com.ademaxweb.msa_messenger.users.api.users.v1.UpdateProfileResponse\"\x00\x12\xaf\x01\n" +
	"\x0eGetProfileByID\x12L.github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByIDRequest\x1aM.github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByIDResponse\"\x00\x12\xc1\x01\n" +
	"\x14GetProfileByNickname\x12R.github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByNicknameRequest\x1aS.github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByNicknameResponse\"\x00\x12\xca\x01\n" +
	"\x17SearchProfileByNickname\x12U.github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameRequest\x1aV.github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameResponse\"\x00B\x15Z\x13pkg/api/users;usersb\x06proto3"

var file_api_users_v1_service_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),            // 0: github.com.ademaxweb.msa_messenger.users.api.users.v1.CreateProfileRequest
	(*UpdateProfileRequest)(nil),            // 1: github.com.ademaxweb.msa_messenger.users.api.users.v1.UpdateProfileRequest
	(*GetProfileByIDRequest)(nil),           // 2: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByIDRequest
	(*GetProfileByNicknameRequest)(nil),     // 3: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByNicknameRequest
	(*SearchProfileByNicknameRequest)(nil),  // 4: github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameRequest
	(*CreateProfileResponse)(nil),           // 5: github.com.ademaxweb.msa_messenger.users.api.users.v1.CreateProfileResponse
	(*UpdateProfileResponse)(nil),           // 6: github.com.ademaxweb.msa_messenger.users.api.users.v1.UpdateProfileResponse
	(*GetProfileByIDResponse)(nil),          // 7: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByIDResponse
	(*GetProfileByNicknameResponse)(nil),    // 8: github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByNicknameResponse
	(*SearchProfileByNicknameResponse)(nil), // 9: github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameResponse
}
var file_api_users_v1_service_proto_depIdxs = []int32{
	0, // 0: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.CreateProfile:input_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.CreateProfileRequest
	1, // 1: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.UpdateProfile:input_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.UpdateProfileRequest
	2, // 2: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.GetProfileByID:input_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByIDRequest
	3, // 3: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.GetProfileByNickname:input_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByNicknameRequest
	4, // 4: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.SearchProfileByNickname:input_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameRequest
	5, // 5: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.CreateProfile:output_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.CreateProfileResponse
	6, // 6: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.UpdateProfile:output_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.UpdateProfileResponse
	7, // 7: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.GetProfileByID:output_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByIDResponse
	8, // 8: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.GetProfileByNickname:output_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.GetProfileByNicknameResponse
	9, // 9: github.com.ademaxweb.msa_messenger.users.api.users.v1.UsersService.SearchProfileByNickname:output_type -> github.com.ademaxweb.msa_messenger.users.api.users.v1.SearchProfileByNicknameResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_users_v1_service_proto_init() }
func file_api_users_v1_service_proto_init() {
	if File_api_users_v1_service_proto != nil {
		return
	}
	file_api_users_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_service_proto_rawDesc), len(file_api_users_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_v1_service_proto_goTypes,
		DependencyIndexes: file_api_users_v1_service_proto_depIdxs,
	}.Build()
	File_api_users_v1_service_proto = out.File
	file_api_users_v1_service_proto_goTypes = nil
	file_api_users_v1_service_proto_depIdxs = nil
}
